<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Linked {client} account.' => '',
    'Unable to save user: {errors}' => '',
    'User with the same email as in {client} account already exists but isn\'t linked to it. Login using email first to link it.' => '',
    'Verify Change' => '@@Проверить транзакции@@',
    '- add -' => '- добавить -',
    '- remove -' => '- списать -',
    'Account' => 'Суб-счет',
    'Account From' => 'Счет - источник',
    'Account To' => 'Счет - приемник',
    'Account used for these transactions' => 'Счет, на который записать эти транзакции',
    'Amount' => 'Сумма',
    'Assets' => 'Активы',
    'Balance History' => 'История',
    'Balance Item' => 'Счет баланса',
    'Balance Sheet' => 'Балансовый месяц',
    'Balance Type' => 'Тип',
    'CSV File' => 'CSV файл',
    'CSV Separator' => 'CSV разделитель',
    'Category' => 'Категория',
    'Create' => 'Создать',
    'Create Transaction' => 'Создать Транзакцию',
    'Create balance to view the totals' => 'Создайте счета, чтобы увидеть сводные данные',
    'Current Balance' => 'Обзор счетов',
    'Date' => 'Дата',
    'Date format, f.e. d/m/Y for 12/05/2017' => 'Формат даты, например d/m/Y для 12/05/2017',
    'Decimal Separator' => 'Разделитель разрядов',
    'Description' => 'Описание',
    'Description Trigger' => 'Ключевая строка в описании',
    'Drop my data' => 'Удалить все счета',
    'Field Amount' => 'Поле суммы',
    'Field Date' => 'Поле даты',
    'Field Date Format' => 'Формат поля даты',
    'Field Description' => 'Поле описания',
    'Finished' => 'Завершен',
    'For Review' => 'На ревью',
    'Home' => 'Главная',
    'Home Finance' => 'Я, финансист',
    'Init wizard' => 'Быстрый старт',
    'Inverse Signs' => 'Обратить знаки',
    'Liabilities' => 'Пассивы',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Manage your money professionally!' => 'Управляй деньгами профессионально!',
    'Mark this if csv presents payments with positive sign' => 'Отметьте, если в файле платежи отражены положительными числами',
    'My Profile' => 'Мой профиль',
    'Name' => 'Имя',
    'New Balance Item' => 'Новый счет',
    'New Month' => 'Новый месяц',
    'Next' => 'Дальше',
    'OR' => 'ИЛИ',
    'Operation Account' => 'Операционный счет',
    'Order Code' => 'Номер',
    'Out of balance assets' => 'Забалансовые активы',
    'Password' => 'Пароль',
    'Period Start' => 'Начало периода',
    'Register' => 'Регистрация',
    'Register Datetime' => 'Дата регистрации',
    'Remember Me' => 'Запомнить меня',
    'Review' => 'Ревью',
    'Review Transaction' => 'Ревью транзакции',
    'Save' => 'Сохранить',
    'Save and Apply' => 'Сохранить и применить к остальным',
    'Setup category' => 'Установить категорию',
    'Specify CSV format' => 'Укажите формат данных',
    'Start' => 'Старт',
    'Sub Category' => 'Подкатегория',
    'The column header with Amounts' => 'Заголовок столбца с суммами',
    'The column header with Dates' => 'Заголовок столбца с датами',
    'The column header with Descriptions' => 'Заголовок столбца с описаниями',
    'Totals' => 'Сводные данные',
    'Transactions' => 'Транзакции',
    'Update Transaction' => 'Редактировать Транзакцию',
    'Update User' => 'Редактировать пользователя',
    'Upload' => 'Загрузить',
    'Upload Transactions' => 'Загрузить транзакции',
    'User' => 'Пользователь',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
    'Wizards' => 'Процессы-помощники',
    'from' => 'от',
];
