<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RefBalanceItem */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ref-balance-item-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'is_calculated')->checkbox() ?>

    <?= $form->field($model, 'is_autogenerated')->checkbox() ?>

    <?= $form->field($model, 'balance_type_id')->dropDownList($model->getAvailableBalanceTypes()) ?>

    <?= $form->field($model, 'knowledge_article_id')->dropDownList($model->getAvailableKnowledgeArticles(), ['prompt'=>'Не выбрано']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
