<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ref Balance Items';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ref-balance-item-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Ref Balance Item', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'is_calculated:boolean',
			'is_autogenerated:boolean',
			[
				'attribute'=>'balance_type_id',
				'value'=>'balanceType.name',
			],
			[
				'attribute'=>'knowledge_article_id',
				'value'=>'knowledgeArticle.name',
			],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
