<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\RefBalanceItem */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Ref Balance Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ref-balance-item-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'is_calculated:boolean',
			'is_autogenerated:boolean',
			[
				'attribute'=>'balance_type_id',
				'value'=>$model->balanceType->name,
			],
			[
				'attribute'=>'knowledge_article_id',
				'value'=>$model->knowledgeArticle->name,
			],
        ],
    ]) ?>

</div>
