<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "ref_balance_item".
 *
 * @property integer $id
 * @property string $name
 * @property integer $is_calculated
 * @property integer $is_autogenerated
 * @property integer $balance_type_id
 * @property integer $knowledge_article_id
 *
 * @property BalanceItem[] $balanceItems
 * @property BalanceType $balanceType
 * @property KnowledgeArticle $knowledgeArticle
 */
class RefBalanceItem extends \yii\db\ActiveRecord
{
	public function getAvailableBalanceTypes() {
		return BalanceType::find()->select(['name', 'id'])->orderBy('order_code')->indexBy('id')->column();
	}
	
	public function getAvailableKnowledgeArticles() {
		return KnowledgeArticle::find()->select(['name', 'id'])->indexBy('id')->column();
	}
	
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ref_balance_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'is_calculated', 'is_autogenerated', 'balance_type_id'], 'required'],
            [['is_calculated', 'is_autogenerated', 'balance_type_id', 'knowledge_article_id'], 'integer'],
            [['name'], 'string', 'max' => 45],
            [['balance_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => BalanceType::className(), 'targetAttribute' => ['balance_type_id' => 'id']],
            [['knowledge_article_id'], 'exist', 'skipOnError' => true, 'targetClass' => KnowledgeArticle::className(), 'targetAttribute' => ['knowledge_article_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'is_calculated' => 'Is Calculated',
            'is_autogenerated' => 'Is Autogenerated',
            'balance_type_id' => 'Balance Type',
            'knowledge_article_id' => 'Knowledge Article',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBalanceItems()
    {
        return $this->hasMany(BalanceItem::className(), ['ref_balance_item_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBalanceType()
    {
        return $this->hasOne(BalanceType::className(), ['id' => 'balance_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKnowledgeArticle()
    {
        return $this->hasOne(KnowledgeArticle::className(), ['id' => 'knowledge_article_id']);
    }
}
